getwd()
setwd("/Users/kimjisu/Desktop/Data_mining/Day02")
owner.df <- read.csv("ownerExample.csv", header = TRUE)
str(owner.df)
install.packages("pROC")
library(pROC)
r <-roc(owner.df$Class, owner.df$Probability)
str(r)
plot.roc(r)
auc(r)
